### ISSUE TITLE
3d part files

### ISSUE THREAD

**Issue by stuij** [rorosaurus/gba-sp-usb-c#2]
Hey there,

Thanks for getting usb c <> usb c working. That's awesome. Maybe I want too much, but I was wondering if you could also put up the model for the bit to fill up the charging port hole. I'm not sure if i'm happy with black, and it'd be nice to have an excuse to fire up the 3d printer.

Thanks!

**Comment by rorosaurus** [comment]
That file is in this repo, it's just a backup of mahko's original upload on Thingiverse: https://github.com/rorosaurus/gba-sp-usb-c/tree/master/references/makho-spacer-stl 🙂
